# src/run_analysis.py
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Configuration ---
# We use the final cleaned file output by clean_data.py
PROCESSED_DATA_DIR = os.path.join(os.path.dirname(__file__), '../data/processed')
INPUT_FILE = os.path.join(PROCESSED_DATA_DIR, 'final_ranked_artists.csv')
RESULTS_DIR = os.path.join(os.path.dirname(__file__), '../results')
os.makedirs(RESULTS_DIR, exist_ok=True)

def load_data():
    """Loads the processed data file."""
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} not found. Please run clean_data.py first.")
        return pd.DataFrame()
    return pd.read_csv(INPUT_FILE)

def create_visualizations(df):
    """Generates and saves the project visualizations."""
    if df.empty:
        return

    print("Generating visualizations...")
    sns.set_theme(style="whitegrid")
    
    # --- FIG 1: Popularity Index Bar Chart ---
    plt.figure(figsize=(12, 6))
    sns.barplot(data=df, x='popularity_score_100', y='artist', palette='viridis')
    plt.title('Combined Popularity Index (Weighted Score)', fontsize=15)
    plt.xlabel('Score (0-100)', fontsize=12)
    plt.ylabel('Artist', fontsize=12)
    plt.axvline(x=50, color='r', linestyle='--', alpha=0.5, label='Average')
    
    out_path_1 = os.path.join(RESULTS_DIR, 'popularity_index_ranking.png')
    plt.tight_layout()
    plt.savefig(out_path_1)
    plt.close()
    print(f"Saved: {out_path_1}")

    # --- FIG 2: Platform Dominance Scatter Plot ---
    # Only if normalization columns exist
    if 'norm_youtube' in df.columns and 'norm_tiktok' in df.columns:
        plt.figure(figsize=(10, 8))
        sns.scatterplot(
            data=df, 
            x='norm_youtube', 
            y='norm_tiktok', 
            s=200, 
            hue='artist', 
            palette='deep', 
            legend=False
        )
        
        # Add labels to points
        for i in range(df.shape[0]):
            plt.text(
                df.norm_youtube[i]+0.02, 
                df.norm_tiktok[i], 
                df.artist[i], 
                fontsize=11, 
                weight='bold'
            )
            
        plt.title('Platform Dominance: YouTube Views vs. TikTok Posts', fontsize=15)
        plt.xlabel('YouTube Dominance (Normalized)', fontsize=12)
        plt.ylabel('TikTok Dominance (Normalized)', fontsize=12)
        plt.grid(True, linestyle='--', alpha=0.7)
        
        out_path_2 = os.path.join(RESULTS_DIR, 'platform_dominance_scatter.png')
        plt.tight_layout()
        plt.savefig(out_path_2)
        plt.close()
        print(f"Saved: {out_path_2}")

def generate_summary_report(df):
    """Generates a text summary of the findings."""
    if df.empty:
        return

    report_path = os.path.join(RESULTS_DIR, 'analysis_summary.txt')
    
    with open(report_path, 'w') as f:
        f.write("=== FINAL PROJECT ANALYSIS REPORT ===\n")
        f.write("Generated by src/run_analysis.py\n\n")
        
        # 1. Top Artist
        top_artist = df.iloc[0]
        f.write(f"WINNER: {top_artist['artist']}\n")
        f.write(f"Popularity Score: {top_artist['popularity_score_100']:.2f}/100\n")
        f.write(f"Stats: {top_artist['youtube_total_views']:,} YouTube Views | {top_artist['tiktok_post_count']:,} TikTok Posts\n\n")
        
        # 2. Full Rankings table
        f.write("--- FULL RANKINGS ---\n")
        # Select relevant columns for clean printing
        cols_to_print = ['rank', 'artist', 'popularity_score_100', 'youtube_total_views', 'tiktok_post_count']
        # Check if columns exist before printing
        existing_cols = [c for c in cols_to_print if c in df.columns]
        f.write(df[existing_cols].to_string(index=False))
        f.write("\n\n")
        
        # 3. Correlation (Simple Insight)
        if 'norm_youtube' in df.columns:
            f.write("--- INSIGHTS ---\n")
            yt_dom = df.sort_values('norm_youtube', ascending=False).iloc[0]['artist']
            tt_dom = df.sort_values('norm_tiktok', ascending=False).iloc[0]['artist']
            f.write(f"Most dominant on YouTube: {yt_dom}\n")
            f.write(f"Most dominant on TikTok: {tt_dom}\n")

    print(f"Saved summary report: {report_path}")
    print("\n--- Preview of Results ---")
    print(df[['rank', 'artist', 'popularity_score_100']].head())

if __name__ == "__main__":
    df = load_data()
    if not df.empty:
        create_visualizations(df)
        generate_summary_report(df)
        print("\nAnalysis Complete! Check the 'results/' folder.")
